### ISSUE TITLE
ADNI converter not able to convert T1 images

### ISSUE THREAD

**Issue by RR979** [aramis-lab/clinica#1010]
Dear Clinica team,
I have been facing conversion problems with ADNI3 T1 images when using the converter (Clinica Version 0.7.6). My unzipped folder has a few subjects and each subject has a MPRAGE T1 folder and RS FMRI folder (before conversion). After conversion, I was able to get the fmri converted successfully into the func folder but the T1 conversion was missing (there was no anat folder). When I tried removing the fmri folders from each subject and tried the conversion for the MPRAGE folders only, usual conversion steps begin but later I get the following error:

2023-10-31 03:49:33,441:INFO:Creating sessions files...
2023-10-31 03:49:33,444:INFO:	Reading clinical data file: ADNIMERGE.csv
2023-10-31 03:49:33,617:INFO:	Reading clinical data file: CDR.csv
2023-10-31 03:49:33,653:INFO:	Reading clinical data file: NEUROBAT.csv
2023-10-31 03:49:33,748:INFO:	Reading clinical data file: ADASSCORES.csv
2023-10-31 03:49:33,762:INFO:	Reading clinical data file: CCI.csv
2023-10-31 03:49:33,768:INFO:	Reading clinical data file: ECOGPT.csv
2023-10-31 03:49:33,806:INFO:	Reading clinical data file: ECOGSP.csv
2023-10-31 03:49:33,846:INFO:	Reading clinical data file: FCI.csv
2023-10-31 03:49:33,863:INFO:	Reading clinical data file: GDSCALE.csv
2023-10-31 03:49:33,897:INFO:	Reading clinical data file: MODHACH.csv
2023-10-31 03:49:33,907:INFO:	Reading clinical data file: MOCA.csv
2023-10-31 03:49:33,940:INFO:	Reading clinical data file: NPI.csv
2023-10-31 03:49:34,015:INFO:	Reading clinical data file: NPIQ.csv
2023-10-31 03:49:34,042:INFO:	Reading clinical data file: BHR_EVERYDAY_COGNITION.csv
2023-10-31 03:49:34,047:INFO:	Reading clinical data file: BHR_BASELINE_QUESTIONNAIRE.csv
2023-10-31 03:49:34,049:INFO:	Reading clinical data file: BHR_LONGITUDINAL_QUESTIONNAIRE.csv
2023-10-31 03:49:34,054:INFO:	Reading clinical data file: MEDHIST.csv
2023-10-31 03:49:34,065:INFO:	Reading clinical data file: VITALS.csv
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/bin/clinica", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/clinica/cmdline.py", line 92, in main
    cli()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/clinica/iotools/converters/adni_to_bids/adni_to_bids_cli.py", line 74, in cli
    adni_to_bids.convert_clinical_data(
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/clinica/iotools/converters/adni_to_bids/adni_to_bids.py", line 147, in convert_clinical_data
    adni_utils.create_adni_sessions_dict(
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/clinica/iotools/converters/adni_to_bids/adni_utils.py", line 980, in create_adni_sessions_dict
    raise ValueError("Empty dataset detected. Clinical data cannot be extracted.")
**ValueError: Empty dataset detected. Clinical data cannot be extracted.**

These are the subjects from my collection (before conversion):
<img width="1680" alt="image" src="https://github.com/aramis-lab/clinica/assets/73432577/f1d8a16d-1164-4361-b387-8cd63c56314b">

These are the folders in each of the collection (before conversion):
<img width="1680" alt="image" src="https://github.com/aramis-lab/clinica/assets/73432577/fc54f59d-e8cd-47c3-b768-557f30105404">

**Comment by MatthieuJoulot** [comment]
Hi @RR979, I'll look into it. I'll look into it. ADNI has been changing some stuff recently and that might be the cause of your trouble.
Have you only downloaded only MPRAGE per subject, or have you followed the instruction we suggest in the documentation ? If not, could you please try to download your collection like we suggest it [here](https://aramislab.paris.inria.fr/clinica/docs/public/latest/Converters/ADNI2BIDS/#downloading-adni) ? It would help greatly !

Have a good day,

**Comment by RR979** [comment]
@MatthieuJoulot that's right, I had only downloaded MPRAGE per subject. My search criteria is as follows:

<img width="145" alt="image" src="https://github.com/aramis-lab/clinica/assets/73432577/c57dcb58-5271-4d1e-ac11-6c004a56a439">

The field strength and matrix Z values narrowed down only the MPRAGE images (since I only wanted original T1 MPRAGE versions)

As you mentioned, I tried the steps given in the documentation which told to include all types of data - original, preprocessed and postprocessed (previously I had only selected original for which the conversion didnt work). The conversion was successful for the preprocessed type of data for T1 images (namely MT1 N3M, MT1 gradwarp N3m, spatially normalized masked and N3 corrected T1 images)

This led me to wonder whether the conversion tool is only supposed to work for preprcoessed T1 images and not original (raw) data. Anyway, devs, thank you for this amazing tool, this is probably the only one out there that helps with ADNI data.

**Comment by scott-gurney** [comment]
I am getting the same error, Python 3.8 Clinica 0.7.6:
Traceback (most recent call last):
  File "/gpfs/home/tqh20wsu/.conda/envs/clinicaEnv/bin/clinica", line 8, in <module>
    sys.exit(main())
  File "/gpfs/home/tqh20wsu/.conda/envs/clinicaEnv/lib/python3.8/site-packages/clinica/cmdline.py", line 92, in main
    cli()
  File "/gpfs/home/tqh20wsu/.conda/envs/clinicaEnv/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/gpfs/home/tqh20wsu/.conda/envs/clinicaEnv/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/gpfs/home/tqh20wsu/.conda/envs/clinicaEnv/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/gpfs/home/tqh20wsu/.conda/envs/clinicaEnv/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/gpfs/home/tqh20wsu/.conda/envs/clinicaEnv/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/gpfs/home/tqh20wsu/.conda/envs/clinicaEnv/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/gpfs/home/tqh20wsu/.conda/envs/clinicaEnv/lib/python3.8/site-packages/clinica/iotools/converters/adni_to_bids/adni_to_bids_cli.py", line 74, in cli
    adni_to_bids.convert_clinical_data(
  File "/gpfs/home/tqh20wsu/.conda/envs/clinicaEnv/lib/python3.8/site-packages/clinica/iotools/converters/adni_to_bids/adni_to_bids.py", line 147, in convert_clinical_data
    adni_utils.create_adni_sessions_dict(
  File "/gpfs/home/tqh20wsu/.conda/envs/clinicaEnv/lib/python3.8/site-packages/clinica/iotools/converters/adni_to_bids/adni_utils.py", line 980, in create_adni_sessions_dict
    raise ValueError("Empty dataset detected. Clinical data cannot be extracted.")
ValueError: Empty dataset detected. Clinical data cannot be extracted.
(clinicaEnv) [tqh20wsu@c0006 ~/Documents/test]$ ValueError: Empty dataset detected. Clinical data cannot be extracted.

Here is my ADNI data:
![image](https://github.com/aramis-lab/clinica/assets/52426901/760b07ff-510b-4ff7-978d-9ff336d86c80)
![image](https://github.com/aramis-lab/clinica/assets/52426901/1e103794-d06c-4761-8818-66c67020b909)
![image](https://github.com/aramis-lab/clinica/assets/52426901/233aae62-8fd0-461b-806f-00911f0fa211)

Output showing no path
![image](https://github.com/aramis-lab/clinica/assets/52426901/71fc5ffa-5db0-4649-8290-1dcf4ac98814)

**Comment by MatthieuJoulot** [comment]
Hi Scott, 
We might not convert the format you have downloaded. The details regarding the conversion logic are available (here)[https://aramislab.paris.inria.fr/clinica/docs/public/latest/Converters/ADNI2BIDS/#advanced-appendix-how-adni-is-converting-into-bids]. Can you try the solution that I suggested above ? It might work for you as well.

Have a good day, 
Matthieu

**Comment by scott-gurney** [comment]
@MatthieuJoulot I believe you have replied to me on the Google groups page, I have also replied there.

**Comment by kl8y86** [comment]
Dear @MatthieuJoulot , 
Since it's now November 30th, I noticed that you mentioned changes in the ADNI clinical data (CSV files). I'm not sure if my errors are caused by these changes. I would greatly appreciate any help you can provide regarding this error. Additionally, regarding the changes you mentioned in the ADNI clinical data (CSV files), what should I do to continue using Clinica to convert ADNI to BIDS?

2023-11-30 12:56:37,882:INFO:Creating sessions files...
2023-11-30 12:56:38,597:INFO:**Clinical dataframe extracted from CCI.csv is empty after filtering.**
2023-11-30 12:56:39,362:INFO:**Clinical dataframe extracted from BHR_EVERYDAY_COGNITION.csv is empty after filtering.**
2023-11-30 12:56:39,418:INFO:**Clinical dataframe extracted from BHR_BASELINE_QUESTIONNAIRE.csv is empty after filtering.**
2023-11-30 12:56:39,448:INFO:Clinical dataframe extracted from BHR_LONGITUDINAL_QUESTIONNAIRE.csv is empty after filtering.
2023-11-30 12:56:39,681:INFO:Creating scans files...
Traceback (most recent call last):
  File "/lyceum/kl2y21/miniconda3/envs/clinicaEnv/bin/clinica", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/lyceum/kl2y21/miniconda3/envs/clinicaEnv/lib/python3.11/site-packages/clinica/cmdline.py", line 92, in main
    cli()
  File "/lyceum/kl2y21/miniconda3/envs/clinicaEnv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lyceum/kl2y21/miniconda3/envs/clinicaEnv/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/lyceum/kl2y21/miniconda3/envs/clinicaEnv/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lyceum/kl2y21/miniconda3/envs/clinicaEnv/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lyceum/kl2y21/miniconda3/envs/clinicaEnv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lyceum/kl2y21/miniconda3/envs/clinicaEnv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lyceum/kl2y21/miniconda3/envs/clinicaEnv/lib/python3.11/site-packages/clinica/iotools/converters/adni_to_bids/adni_to_bids_cli.py", line 79, in cli
    adni_to_bids.convert_clinical_data(
  File "/lyceum/kl2y21/miniconda3/envs/clinicaEnv/lib/python3.11/site-packages/clinica/iotools/converters/adni_to_bids/adni_to_bids.py", line 152, in convert_clinical_data
    adni_utils.create_adni_scans_files(conversion_path, bids_subjs_paths)
  File "/lyceum/kl2y21/miniconda3/envs/clinicaEnv/lib/python3.11/site-packages/clinica/iotools/converters/adni_to_bids/adni_utils.py", line 1108, in create_adni_scans_files
    converted_mod = find_conversion_mod(file_name)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lyceum/kl2y21/miniconda3/envs/clinicaEnv/lib/python3.11/site-packages/clinica/iotools/converters/adni_to_bids/adni_utils.py", line 1149, in find_conversion_mod
    **raise ValueError(f"Conversion modality could not be found for file {file_name}")
ValueError: Conversion modality could not be found for file sub-ADNI002S0413_ses-M108_FLAIR_real.nii**

Is the method for downloading ADNI data as described in the documentation (as shown in the image) still valid, or do we need to follow new instructions to complete the conversion to BIDS?
![图片_20231130222021](https://github.com/aramis-lab/clinica/assets/95025551/16a29f78-e7f7-437b-8330-8820e2620acc)

**Comment by MatthieuJoulot** [comment]
Hi @kl8y86, 
We just released a new version of Clinica (0.7.7) which tackles the issue of the changes in the csv names. You can download them following the instructions we provide, these are still valid !

The issue you encounter is due to dcm2niix not being able to convert that specific file. What version of dcm2niix are you using ?

**Comment by kl8y86** [comment]
@MatthieuJoulot 
(clinicaEnv) [kl2y21@cyan51 ~]$ **dcm2niix --version**
Chris Rorden's dcm2niiX version v1.0.20190902  (JP2:OpenJPEG) GCC4.8.2 (64-bit Linux)
v1.0.20190902

My version of dcm2niiX is v1.0.20190902, maybe I need to update it?

**Comment by ghisvail** [comment]
> My version of dcm2niiX is v1.0.20190902, maybe I need to update it?

Indeed

**Comment by kl8y86** [comment]
@MatthieuJoulot @ghisvail 
My command was:
**clinica -v convert adni-to-bids 'DATASET_DIRECTORY' 'CLINICAL_DATA_DIRECTORY' 'ADNI_converted' -m T1**

However, I'm still encountering the following error, and I've been struggling with it for hours now.
2023-12-01 15:50:42,517:INFO:Creating sessions files...
2023-12-01 15:50:42,866:INFO:Clinical dataframe extracted from ADNIMERGE.csv is empty after filtering.
2023-12-01 15:50:42,979:INFO:Clinical dataframe extracted from CDR.csv is empty after filtering.
2023-12-01 15:50:43,219:INFO:Clinical dataframe extracted from NEUROBAT.csv is empty after filtering.
2023-12-01 15:50:43,273:INFO:Clinical dataframe extracted from ADASSCORES.csv is empty after filtering.
2023-12-01 15:50:43,306:INFO:Clinical dataframe extracted from CCI.csv is empty after filtering.
2023-12-01 15:50:43,399:INFO:Clinical dataframe extracted from ECOGPT.csv is empty after filtering.
2023-12-01 15:50:43,485:INFO:Clinical dataframe extracted from ECOGSP.csv is empty after filtering.
2023-12-01 15:50:43,536:INFO:Clinical dataframe extracted from FCI.csv is empty after filtering.
2023-12-01 15:50:43,621:INFO:Clinical dataframe extracted from GDSCALE.csv is empty after filtering.
2023-12-01 15:50:43,693:INFO:Clinical dataframe extracted from MODHACH.csv is empty after filtering.
2023-12-01 15:50:43,804:INFO:Clinical dataframe extracted from MOCA.csv is empty after filtering.
2023-12-01 15:50:43,969:INFO:Clinical dataframe extracted from NPI.csv is empty after filtering.
2023-12-01 15:50:44,038:INFO:Clinical dataframe extracted from NPIQ.csv is empty after filtering.
2023-12-01 15:50:44,056:INFO:Clinical dataframe extracted from BHR_EVERYDAY_COGNITION.csv is empty after filtering.
2023-12-01 15:50:44,119:INFO:Clinical dataframe extracted from BHR_BASELINE_QUESTIONNAIRE.csv is empty after filtering.
2023-12-01 15:50:44,152:INFO:Clinical dataframe extracted from BHR_LONGITUDINAL_QUESTIONNAIRE.csv is empty after filtering.
2023-12-01 15:50:44,241:INFO:Clinical dataframe extracted from MEDHIST.csv is empty after filtering.
Traceback (most recent call last):
  File "/lyceum/kl2y21/miniconda3/envs/clinicaEnv/bin/clinica", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/lyceum/kl2y21/miniconda3/envs/clinicaEnv/lib/python3.11/site-packages/clinica/cmdline.py", line 92, in main
    cli()
  File "/lyceum/kl2y21/miniconda3/envs/clinicaEnv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lyceum/kl2y21/miniconda3/envs/clinicaEnv/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/lyceum/kl2y21/miniconda3/envs/clinicaEnv/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lyceum/kl2y21/miniconda3/envs/clinicaEnv/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lyceum/kl2y21/miniconda3/envs/clinicaEnv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lyceum/kl2y21/miniconda3/envs/clinicaEnv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lyceum/kl2y21/miniconda3/envs/clinicaEnv/lib/python3.11/site-packages/clinica/iotools/converters/adni_to_bids/adni_to_bids_cli.py", line 79, in cli
    adni_to_bids.convert_clinical_data(
  File "/lyceum/kl2y21/miniconda3/envs/clinicaEnv/lib/python3.11/site-packages/clinica/iotools/converters/adni_to_bids/adni_to_bids.py", line 145, in convert_clinical_data
    adni_utils.create_adni_sessions_dict(
  File "/lyceum/kl2y21/miniconda3/envs/clinicaEnv/lib/python3.11/site-packages/clinica/iotools/converters/adni_to_bids/adni_utils.py", line 971, in create_adni_sessions_dict
    **raise ValueError("Empty dataset detected. Clinical data cannot be extracted.")
ValueError: Empty dataset detected. Clinical data cannot be extracted.**

I believe that both my data and the clinical data should follow the rules outlined in the document. I'm using the latest versions of dcm2niiX (v1.0.20190902) and Clinica (0.7.7). Could the reason for this error be an issue with my command?"
![image](https://github.com/aramis-lab/clinica/assets/95025551/d634563f-c3e5-45ae-90e7-b92fb443d05a)
![image](https://github.com/aramis-lab/clinica/assets/95025551/d67491c1-b80f-421f-9512-774ddd440cbe)

**Comment by MatthieuJoulot** [comment]
Yes @kl8y86, it seems your version of dcm2niix is outdated. The current version is v1.0.2022050. Could you use that one, and tell us if it works ?
